from __future__ import annotations

from app.agent.state import NutritionTargets


# Values below are the explicit macro model used by Forma. Calories are always
# calculated from macros, so the total shown to the user can be verified.
BASE_MENU = (
    ("Завтрак", "Овсянка", "40 г", 5.2, 2.8, 24.8),
    ("Завтрак", "Яйца", "2 шт.", 12.0, 10.0, 1.0),
    ("Завтрак", "Сывороточный протеин", "30 г", 24.0, 2.0, 3.0),
    ("Обед", "Куриная грудка", "170 г", 52.7, 6.0, 0.0),
    ("Обед", "Гречка, готовая", "80 г", 2.7, 0.5, 16.0),
    ("Обед", "Овощи", "200 г", 4.0, 0.0, 12.0),
    ("Обед", "Оливковое масло", "10 г", 0.0, 10.0, 0.0),
    ("Перекус", "Творог 5%", "180 г", 28.8, 9.0, 5.4),
    ("Перекус", "Яблоко", "1 среднее", 0.0, 0.0, 21.0),
    ("Перекус", "Орехи", "25 г", 5.0, 12.5, 5.0),
    ("Ужин", "Белая рыба", "190 г", 39.9, 13.3, 0.0),
    ("Ужин", "Рис, готовый", "80 г", 2.0, 0.3, 22.4),
    ("Ужин", "Овощи", "200 г", 4.0, 0.0, 12.0),
    ("Ужин", "Оливковое масло", "10 г", 0.0, 10.0, 0.0),
)

ZEPHYR_SWAP = (
    ("Обед", "Гречка, готовая", "80 г → 0 г", -2.7, -0.5, -16.0),
    ("Ужин", "Рис, готовый", "80 г → 60 г", -0.5, -0.1, -5.6),
    ("Перекус", "Зефир", "30 г", 0.0, 0.0, 22.0),
)


def build_daily_menu(targets: NutritionTargets, include_zephyr: bool = False, language: str = "ru") -> str:
    """Build a stored, auditable daily menu and show its computed macro total."""
    foods = BASE_MENU + (ZEPHYR_SWAP if include_zephyr else ())
    protein = round(sum(item[3] for item in foods))
    fat = round(sum(item[4] for item in foods))
    carbs = round(sum(item[5] for item in foods))
    kcal = protein * 4 + fat * 9 + carbs * 4

    if language == "en":
        return _english_menu(targets, include_zephyr, kcal, protein, fat, carbs)

    meals: dict[str, list[str]] = {}
    for meal, food, amount, *_ in foods:
        if "→ 0 г" in amount:
            continue
        meals.setdefault(meal, []).append(f"{food} — {amount}")
    lines = [
        "Готовый рацион на день" + (" с зефиром" if include_zephyr else "") + ".",
        "Все цифры ниже рассчитаны из встроенной базы порций, а не придуманы моделью.",
        "",
    ]
    for meal in ("Завтрак", "Обед", "Перекус", "Ужин"):
        lines.append(f"**{meal}:** " + "; ".join(meals[meal]) + ".")
    if include_zephyr:
        lines.extend(["", "Зефир 30 г заменяет 80 г гречки и 20 г готового риса — углеводы остаются почти на том же уровне."])
    lines.extend(
        [
            "",
            _summary_ru(targets, kcal, protein, fat, carbs),
            "Чтобы изменить рацион, напишите конкретно: «добавить зефир 30 г» или «показать рацион без зефира».",
        ]
    )
    return "\n".join(lines)


def _summary_ru(targets: NutritionTargets, kcal: int, protein: int, fat: int, carbs: int) -> str:
    return (
        f"**Итог меню:** {kcal} ккал, Б/Ж/У: {protein}/{fat}/{carbs} г. "
        f"**Цель:** {targets.target_kcal} ккал, Б/Ж/У: {targets.protein_g}/{targets.fat_g}/{targets.carbs_g} г. "
        f"Разница: {_signed(kcal - targets.target_kcal)} ккал, "
        f"Б {_signed(protein - targets.protein_g)} г, Ж {_signed(fat - targets.fat_g)} г, У {_signed(carbs - targets.carbs_g)} г."
    )


def _english_menu(targets: NutritionTargets, include_zephyr: bool, kcal: int, protein: int, fat: int, carbs: int) -> str:
    suffix = " with 30 g zephyr" if include_zephyr else ""
    return (
        f"Ready-made daily menu{suffix}. Its totals are calculated from the stored portions, not generated by the model.\n\n"
        "Breakfast: oats 40 g, 2 eggs, whey protein 30 g.\n"
        "Lunch: chicken breast 170 g, cooked buckwheat 80 g, vegetables 200 g, olive oil 10 g.\n"
        "Snack: cottage cheese 5% 180 g, apple, nuts 25 g.\n"
        "Dinner: white fish 190 g, cooked rice 80 g, vegetables 200 g, olive oil 10 g.\n\n"
        f"Menu total: {kcal} kcal, P/F/C {protein}/{fat}/{carbs} g. "
        f"Target: {targets.target_kcal} kcal, P/F/C {targets.protein_g}/{targets.fat_g}/{targets.carbs_g} g."
    )


def _signed(value: int) -> str:
    return f"{value:+d}"
